name = "spaced-blog"
license = "MIT"
licenselink = "https://github.com/Morgscode/spaced-hugo-theme/blob/master/LICENSE"
description = "A beautifully simplistic blog theme. Mobile responsive, dark mode, a11y support and page search out of the box."

homepage = "https://github.com/Morgscode/hugo-theme-spaced-blog"
demosite = "https://blog.luke-morgan.com"
tags = ["Minimalistic", "Dark mode", "Blog", "Responsive", "Dark", "Light"]
features = ["Dark mode", "a11y", "Responsive", "Search"]
min_version = "0.41.0"

[author]
  name = "Luke Morgan"
  homepage = "https://luke-morgan.com"
