name = "spaced"
license = "MIT"
licenselink = "https://github.com/Morgscode/spaced-hugo-theme/blob/master/LICENSE"
description = "A minimalistic blog theme."
homepage = "htts://spaced.luke-morgan.com"
tags = ["Minimalistic", "Dark mode", "Blog"]
features = ["Dark mode", "a11y"]
min_version = "0.41.0"

[author]
  name = "Luke Morgan"
  homepage = "https://luke-morgan.com"
